name = "sfc-terminal"
main = "worker/index.js"
compatibility_date = "2025-06-01"

[observability]
enabled = false

[[kv_namespaces]]
binding = "SFC_USER_STATE"
id = "384c3b360c92484a84eb3e1ecad18a4d"

[env.production]
name = "sfc-terminal"
[[env.production.kv_namespaces]]
binding = "SFC_USER_STATE"
id = "384c3b360c92484a84eb3e1ecad18a4d"
