// sfc-terminal Cloudflare Worker
// Proxies frontend + SSE to VPS via Cloudflare Tunnel
//
// Worker tries multiple backends in order:
// 1. Cloudflare Tunnel (set via env TUNNEL_URL or hardcoded below)
// 2. Direct VPS IP (blocked by some Tencent Cloud security groups)

const TUNNEL = 'https://galleries-actively-grew-require.trycloudflare.com';
const BACKUP = 'http://43.134.89.23:8765';

async function fetchAny(urls, path, accept) {
  for (const base of urls) {
    try {
      const resp = await fetch(base + path, {
        headers: { 'Accept': accept || '*/*' },
        signal: AbortSignal.timeout(5000),
      });
      if (resp.ok) return resp;
    } catch (_) {}
  }
  return null;
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const urls = [TUNNEL, BACKUP];

    // CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'GET, OPTIONS',
          'Access-Control-Allow-Headers': '*',
        },
      });
    }

    // /events — SSE stream generated by worker polling /snapshot
    // (Tunnel can't proxy SSE streaming — edge cancels long-lived streams)
    if (path === '/events') {
      // Pre-check: if backend unreachable, return 502 immediately
      // This forces browser EventSource to retry until worker is updated
      const preCheck = await fetchAny(urls, '/snapshot', 'application/json');
      if (!preCheck) return new Response('Backend unreachable', { status: 502 });

      const { readable, writable } = new TransformStream();
      const writer = writable.getWriter();
      const encoder = new TextEncoder();

      async function pollAndStream() {
        let lastBtcKey = null;
        let lastSfcTs = null;
        let failCount = 0;
        const MAX_FAIL = 5; // ~5s of failures before forcing reconnect
        try {
          for (;;) {
            const resp = await fetchAny(urls, '/snapshot', 'application/json');
            if (resp) {
              failCount = 0; // reset on success
              const data = await resp.json();
              const now = new Date().toISOString();

              // BTC ticker event (only if price changed)
              if (data.btc && data.btc.btc != null) {
                const key = Math.round(data.btc.btc * 100);
                if (key !== lastBtcKey) {
                  lastBtcKey = key;
                  const payload = {
                    price: data.btc.btc,
                    change_pct: data.btc.change_pct || 0,
                    high_24h: data.btc.high_24h || 0,
                    low_24h: data.btc.low_24h || 0,
                    volume_24h: data.btc.volume_24h || 0,
                    ts: data.btc.ts || now,
                  };
                  await writer.write(encoder.encode(
                    'event: btc_ticker\ndata: ' + JSON.stringify(payload) + '\n\n'
                  ));
                }
              }

              // SFC update event (only if data changed)
              if (data.sfc && data.sfc.ts !== lastSfcTs) {
                lastSfcTs = data.sfc.ts;
                await writer.write(encoder.encode(
                  'event: sfc_update\ndata: ' + JSON.stringify(data.sfc) + '\n\n'
                ));
              }
            }

            // Heartbeat every poll
            await writer.write(encoder.encode(
              'event: heartbeat\ndata: {"ts":"' + new Date().toISOString() + '"}\n\n'
            ));

            // If backend unreachable for MAX_FAIL consecutive polls, close the stream
            // so the browser reconnects and hits the (possibly updated) worker
            if (!resp) {
              failCount++;
              if (failCount >= MAX_FAIL) {
                await writer.close();
                break;
              }
            }

            await new Promise(r => setTimeout(r, 1000));
          }
        } catch (_) {
          // Client disconnected or poll failed — stop
        }
      }

      ctx.waitUntil(pollAndStream());

      return new Response(readable, {
        status: 200,
        headers: {
          'Content-Type': 'text/event-stream',
          'Cache-Control': 'no-cache',
          'Connection': 'keep-alive',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    // /snapshot — initial data
    if (path === '/snapshot') {
      const resp = await fetchAny(urls, '/snapshot', 'application/json');
      if (!resp) return new Response('Backend unreachable', { status: 502 });
      const data = await resp.json();
      return new Response(JSON.stringify(data), {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Cache-Control': 'no-cache',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    // /paper_history.json — paper trading track record
    if (path === '/paper_history.json') {
      const resp = await fetchAny(urls, '/paper_history.json', 'application/json');
      if (!resp) return new Response('{"daily":[],"current":{}}', {
        status: 200,
        headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', 'Access-Control-Allow-Origin': '*' },
      });
      const data = await resp.json();
      return new Response(JSON.stringify(data), {
        status: 200,
        headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', 'Access-Control-Allow-Origin': '*' },
      });
    }

    // /paper_trades.json — paper trading server state (for client-side init)
    if (path === '/paper_trades.json') {
      const resp = await fetchAny(urls, '/paper_trades.json', 'application/json');
      if (!resp) return new Response('{"capital":50000,"positions":[],"trades":[],"equity_history":[],"daily_snapshots":{}}', {
        status: 200,
        headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', 'Access-Control-Allow-Origin': '*' },
      });
      const data = await resp.json();
      return new Response(JSON.stringify(data), {
        status: 200,
        headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-cache', 'Access-Control-Allow-Origin': '*' },
      });
    }

    // /health
    if (path === '/health') {
      const resp = await fetchAny(urls, '/health', 'application/json');
      if (!resp) return new Response('Backend unreachable', { status: 502 });
      const data = await resp.json();
      return new Response(JSON.stringify(data), {
        status: 200,
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      });
    }

    // / — index.html
    if (path === '/' || path === '') {
      const resp = await fetchAny(urls, '/', 'text/html');
      if (!resp) return new Response('Backend unreachable', { status: 502 });
      const html = await resp.text();
      return new Response(html, {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'public, max-age=0, must-revalidate',
        },
      });
    }

    return new Response('Not Found', { status: 404 });
  },
};
